org: lombardi
service: afp-hospital

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role: ${file(./credentials.yml):IAM.role}
  environment:
    db_host: ${file(./credentials.yml):ENV.db_host}
    user: ${file(./credentials.yml):ENV.user}
    password: ${file(./credentials.yml):ENV.password}
    database: ${file(./credentials.yml):ENV.database}
    port: ${file(./credentials.yml):ENV.port}

functions:
  endpoints:
    handler: handler.endpoints
    events:
      - httpApi:
          path: /
          method: get
  lista-ospedali:
    handler: ospedali.listaOspedali
    events:
      - httpApi:
          path: /lista-ospedali
          method: get
  lista-reparti-all:
    handler: reparti.listaReparti
    events:
      - httpApi:
          path: /lista-reparti
          method: get
  lista-reparti:
    handler: reparti.listaReparti
    events:
      - httpApi:
          path: /lista-reparti/{ospedaleId}
          method: get
  lista-pz-all:
    handler: pazienti.listaPz
    events:
      - httpApi:
          path: /lista-pz
          method: get
  lista-pz:
    handler: pazienti.listaPz
    events:
      - httpApi:
          path: /lista-pz/{ospedaleId}
          method: get
  accetta-pz:
    handler: pazienti.accettaPz
    events:
      - httpApi:
          path: /accetta-pz
          method: post
  modifica-pz:
    handler: pazienti.modificaPz
    events:
      - httpApi:
          path: /modifica-pz/{id}
          method: put
  trasferisci-pz:
    handler: pazienti.trasferisciPz
    events:
      - httpApi:
          path: /trasferisci-pz/{id}
          method: put
  dimetti-pz:
    handler: pazienti.dimettiPz
    events:
      - httpApi:
          path: /dimetti-pz/{id}
          method: delete


plugins:
  - serverless-offline
